### ISSUE TITLE
encoding issue on a strange (invalid?) username in follow history

### ISSUE THREAD

**Issue by Netherdrake** [steemit/hivemind#21] opened 2017-09-27 00:10 UTC
I guess the follow plugin doesn't necessarily enforce constraints on what is a valid username, and there is one with `Ȃ` in it. 

It breaks hive indexer like this:
```
INFO:sqlalchemy.engine.base.Engine:
        INSERT IGNORE INTO hive_follows (follower, following, created_at, state)
        VALUES (%s, %s, %s, %s) ON DUPLICATE KEY UPDATE state = %s
        
INFO:sqlalchemy.engine.base.Engine:('tuakanamorgan', 'najem\u202c', '2017-06-27T20:42:03', 1, 1)
INFO:sqlalchemy.engine.base.Engine:ROLLBACK
Traceback (most recent call last):
  File "/usr/local/bin/hive", line 9, in <module>
    load_entry_point('hivemind', 'console_scripts', 'hive')()
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/app/hive/indexer/cli.py", line 22, in index_from_steemd
    run()
  File "/app/hive/indexer/core.py", line 421, in run
    sync_from_steemd(is_initial_sync)
  File "/app/hive/indexer/core.py", line 335, in sync_from_steemd
    dirty |= process_blocks(blocks, is_initial_sync)
  File "/app/hive/indexer/core.py", line 278, in process_blocks
    dirty |= process_block(block, is_initial_sync)
  File "/app/hive/indexer/core.py", line 264, in process_block
    process_json_follow_op(account, op_json, date)
  File "/app/hive/indexer/core.py", line 173, in process_json_follow_op
    query(sql, fr=follower, fg=following, at=block_date, state=state)
  File "/app/hive/db/methods.py", line 17, in query
    res = conn.execute(query, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 1405, in _handle_dbapi_exception
    util.reraise(*exc_info)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/util/compat.py", line 187, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.5/dist-packages/MySQLdb/cursors.py", line 234, in execute
    args = tuple(map(db.literal, args))
  File "/usr/local/lib/python3.5/dist-packages/MySQLdb/connections.py", line 318, in literal
    s = self.escape(o, self.encoders)
  File "/usr/local/lib/python3.5/dist-packages/MySQLdb/connections.py", line 225, in unicode_literal
    return db.string_literal(str(u).encode(db.encoding))
UnicodeEncodeError: 'latin-1' codec can't encode character '\u202c' in position 5: ordinal not in range(256)
```

**Comment by roadscape** [comment] 2017-09-27 00:19
Seems to be an issue with `is_valid_account_name` because the op gets ignored unless both `follower` and `following` are valid. However, locally see that `is_valid_account_name('aaaaȂ') == None`

**Comment by roadscape** [comment] 2017-11-17 16:23
We'll be tracking all account names so we can do away with `is_valid_account_name`. Also, I haven't seen this error, and we're moving to postgres. Please reopen later if issue happens to re-arise.

**Comment by sneak** [comment] 2017-11-17 18:01
No, we’re moving to a superset of mysql+postgres - please don’t break existing compatability. :)

Not everyone will have the luxury of us of dedicating a local DB container to hivemind.  MySQL is far more common and people already have mysql db servers around they will want to add a database to.  If you want hivemind’s consensus opinions to become a standard, then it needs to support MySQL for other sites to use. :)

**Comment by sneak** [comment] 2017-11-17 18:02
The way I would like to see bugs like this closed is with a PR that adds a test that proves it’s closed. :)

**Comment by roadscape** [comment] 2017-11-17 18:03
Ok, noted, but this issue is still a non-issue IMO. Not reproducible and the function that seems to be misbehaving in this case is going away. Let's close it.

**Closed** 2017-11-17 19:55 UTC
Labels: bug
